"""Create permanent student models and financial foundation

Revision ID: 29c8a27fda72
Revises: 
Create Date: 2025-11-11 13:18:05.172917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29c8a27fda72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint(batch_op.f('parents_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('lead_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('enrollment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('lead_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_unique_constraint(None, ['student_id_number'])
        batch_op.drop_column('city_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_state', mysql.VARCHAR(length=150), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('lead_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('enrollment_date')
        batch_op.drop_column('status')
        batch_op.drop_column('student_id_number')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('parents_ibfk_1'), 'leads', ['lead_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
